before_script:
  - npm install

production:
  stage: build
  image: alles.was.zerkabelt.de/static-os:latest
  script:
    - webpack --optimize-minimize --output-path dist
  artifacts:
    paths:
      - dist
